apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: catalog
  labels:
    app: catalog-service
  name: catalog-service
spec:
  selector:
    matchLabels:
      app: catalog-service
  strategy: {}
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - image: luskidotme/catalog-service:v1
        imagePullPolicy: Always
        name: catalog-api
        ports:
        - containerPort: 3333
        env:
        - name: REDIS_ADDR
          value: "redis-master:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog-service
  name: catalog-service
  namespace: catalog
spec:
  ports:
  - port: 3333
    protocol: TCP
    targetPort: 3333
  selector:
    app: catalog-service
status:
  loadBalancer: {}
