apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog
  name: blog
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  strategy: {}
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: luskidotme/blog:v1
        name: blog
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
  namespace: blog
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
    targetPort: 8080
    nodePort: 31388 # mapped to localhost:8080 through hostPort
  selector:
    app: blog
  type: NodePort